language: node_js
node_js:
- v8
- v10
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- echo "testnet.exchange,104.196.1.222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH5YNl+kx9CPNqCPmHfjWWea/wihgMJP8E6Bp3HrNnl0it+O916PHCJ+Dk8j2TadaleuT7NxA3BDXIo1qKUq/ys="
  >> ~/.ssh/known_hosts
- npm run connect-xchange
- npm test -- -i --coverage
after_success:
  skip_cleanup: true
  script:
  - ssh -i travis caffeinum@testnet.exchange "cd /home/caffeinum/testXback && git pull"
  on:
    branch: master
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
before_install:
- openssl aes-256-cbc -K $encrypted_1dbd2aab2682_key -iv $encrypted_1dbd2aab2682_iv
  -in travis.enc -out travis -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis
- echo -e "Host testnet.exchange\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis
