language: node_js
node_js:
- v8
- v10
services:
  - mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm run connect-xchange
  - npm test -- -i --coverage
deploy:
  skip_cleanup: true
  script:
    - ssh caffeinum@testnet.exchange "cd /home/caffeinum/testXback && git pull"
  on:
    branch: master
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
